rust:
  repo: https://github.com/matrix-org/matrix-rust-sdk
  ref: 265abd6830363a2be89017d6d8abd2353170fd21
  manifestPath: bindings/matrix-sdk-ffi/Cargo.toml
web:
  workspace: true
  manifestPath: rust_modules/matrix-rust-sdk/bindings/wasm/Cargo.toml
  features: ["native-tls", "js", "indexeddb"]
  defaultFeatures: false
